Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from rdflib import Namespace
from buildingmotif import BuildingMOTIF
from buildingmotif.dataclasses import Model, Library
from buildingmotif.namespaces import BRICK # import this to make writing URIs easier

# in-memory instance
bm = BuildingMOTIF("sqlite://")

# create the namespace for the building
BLDG = Namespace('urn:bldg/')

# create the building model
model = Model.create(BLDG, description="This is a test model for a simple building")

# load tutorial 1 model
model.graph.parse("tutorial1_model.ttl", format="ttl")

# load libraries included with the python package
constraints = Library.load(ontology_graph="../../buildingmotif/libraries/constraints/constraints.ttl")

# load libraries excluded from the python package (available from the repository)
brick = Library.load(ontology_graph="../../libraries/brick/Brick-subset.ttl")
g36 = Library.load(directory="../../libraries/ashrae/guideline36")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIntegrityError[0m                            Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1910[0m, in [0;36mConnection._execute_context[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)[0m
[1;32m   1909[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m evt_handled:
[0;32m-> 1910[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdialect[49m[38;5;241;43m.[39;49m[43mdo_execute[49m[43m([49m
[1;32m   1911[0m [43m            [49m[43mcursor[49m[43m,[49m[43m [49m[43mstatement[49m[43m,[49m[43m [49m[43mparameters[49m[43m,[49m[43m [49m[43mcontext[49m
[1;32m   1912[0m [43m        [49m[43m)[49m
[1;32m   1914[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_has_events [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39mengine[38;5;241m.[39m_has_events:

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py:736[0m, in [0;36mDefaultDialect.do_execute[0;34m(self, cursor, statement, parameters, context)[0m
[1;32m    735[0m [38;5;28;01mdef[39;00m [38;5;21mdo_execute[39m([38;5;28mself[39m, cursor, statement, parameters, context[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 736[0m     cursor[38;5;241m.[39mexecute(statement, parameters)

[0;31mIntegrityError[0m: UNIQUE constraint failed: template.name, template.library_id

The above exception was the direct cause of the following exception:

[0;31mIntegrityError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 23[0m
[1;32m     21[0m [38;5;66;03m# load libraries excluded from the python package (available from the repository)[39;00m
[1;32m     22[0m brick [38;5;241m=[39m Library[38;5;241m.[39mload(ontology_graph[38;5;241m=[39m[38;5;124m"[39m[38;5;124m../../libraries/brick/Brick-subset.ttl[39m[38;5;124m"[39m)
[0;32m---> 23[0m g36 [38;5;241m=[39m [43mLibrary[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mdirectory[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m../../libraries/ashrae/guideline36[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/library.py:194[0m, in [0;36mLibrary.load[0;34m(cls, db_id, ontology_graph, directory, name, overwrite)[0m
[1;32m    192[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m src[38;5;241m.[39mexists():
[1;32m    193[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mDirectory [39m[38;5;132;01m{[39;00msrc[38;5;132;01m}[39;00m[38;5;124m does not exist[39m[38;5;124m"[39m)
[0;32m--> 194[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mcls[39;49m[38;5;241;43m.[39;49m[43m_load_from_directory[49m[43m([49m[43msrc[49m[43m,[49m[43m [49m[43moverwrite[49m[38;5;241;43m=[39;49m[43moverwrite[49m[43m)[49m
[1;32m    195[0m [38;5;28;01melif[39;00m name [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    196[0m     bm [38;5;241m=[39m get_building_motif()

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/library.py:343[0m, in [0;36mLibrary._load_from_directory[0;34m(cls, directory, overwrite)[0m
[1;32m    341[0m [38;5;66;03m# read all .yml files[39;00m
[1;32m    342[0m [38;5;28;01mfor[39;00m file [38;5;129;01min[39;00m directory[38;5;241m.[39mrglob([38;5;124m"[39m[38;5;124m*.yml[39m[38;5;124m"[39m):
[0;32m--> 343[0m     [43mlib[49m[38;5;241;43m.[39;49m[43m_read_yml_file[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[43mtemplate_id_lookup[49m[43m,[49m[43m [49m[43mdependency_cache[49m[43m)[49m
[1;32m    344[0m [38;5;66;03m# now that we have all the templates, we can populate the dependencies[39;00m
[1;32m    345[0m lib[38;5;241m.[39m_resolve_template_dependencies(template_id_lookup, dependency_cache)

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/library.py:477[0m, in [0;36mLibrary._read_yml_file[0;34m(self, file, template_id_lookup, dependency_cache)[0m
[1;32m    473[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[1;32m    474[0m     logging[38;5;241m.[39merror(
[1;32m    475[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mError creating template [39m[38;5;132;01m{[39;00mtempl_name[38;5;132;01m}[39;00m[38;5;124m from file [39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    476[0m     )
[0;32m--> 477[0m     [38;5;28;01mraise[39;00m e
[1;32m    478[0m dependency_cache[templ[38;5;241m.[39mid] [38;5;241m=[39m deps
[1;32m    479[0m template_id_lookup[templ[38;5;241m.[39mname] [38;5;241m=[39m templ[38;5;241m.[39mid

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/library.py:472[0m, in [0;36mLibrary._read_yml_file[0;34m(self, file, template_id_lookup, dependency_cache)[0m
[1;32m    470[0m templ_spec[[38;5;124m"[39m[38;5;124moptional_args[39m[38;5;124m"[39m] [38;5;241m=[39m templ_spec[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moptional[39m[38;5;124m"[39m, [])
[1;32m    471[0m [38;5;28;01mtry[39;00m:
[0;32m--> 472[0m     templ [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcreate_template[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mtempl_spec[49m[43m)[49m
[1;32m    473[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[1;32m    474[0m     logging[38;5;241m.[39merror(
[1;32m    475[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mError creating template [39m[38;5;132;01m{[39;00mtempl_name[38;5;132;01m}[39;00m[38;5;124m from file [39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    476[0m     )

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/dataclasses/library.py:527[0m, in [0;36mLibrary.create_template[0;34m(self, name, body, optional_args)[0m
[1;32m    510[0m [38;5;28;01mdef[39;00m [38;5;21mcreate_template[39m(
[1;32m    511[0m     [38;5;28mself[39m,
[1;32m    512[0m     name: [38;5;28mstr[39m,
[1;32m    513[0m     body: Optional[rdflib[38;5;241m.[39mGraph] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m    514[0m     optional_args: Optional[List[[38;5;28mstr[39m]] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m    515[0m ) [38;5;241m-[39m[38;5;241m>[39m Template:
[1;32m    516[0m [38;5;250m    [39m[38;5;124;03m"""Create template in this library.[39;00m
[1;32m    517[0m 
[1;32m    518[0m [38;5;124;03m    :param name: name[39;00m
[0;32m   (...)[0m
[1;32m    525[0m [38;5;124;03m    :rtype: Template[39;00m
[1;32m    526[0m [38;5;124;03m    """[39;00m
[0;32m--> 527[0m     db_template [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_bm[49m[38;5;241;43m.[39;49m[43mtable_connection[49m[38;5;241;43m.[39;49m[43mcreate_db_template[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_id[49m[43m)[49m
[1;32m    528[0m     body [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_bm[38;5;241m.[39mgraph_connection[38;5;241m.[39mcreate_graph(
[1;32m    529[0m         db_template[38;5;241m.[39mbody_id, body [38;5;28;01mif[39;00m body [38;5;28;01melse[39;00m rdflib[38;5;241m.[39mGraph()
[1;32m    530[0m     )
[1;32m    531[0m     [38;5;66;03m# ensure the "param" namespace is bound to the graph[39;00m

File [0;32m~/work/BuildingMOTIF/BuildingMOTIF/buildingmotif/database/table_connection.py:280[0m, in [0;36mTableConnection.create_db_template[0;34m(self, name, library_id)[0m
[1;32m    272[0m template [38;5;241m=[39m DBTemplate(
[1;32m    273[0m     name[38;5;241m=[39mname,
[1;32m    274[0m     body_id[38;5;241m=[39m[38;5;28mstr[39m(uuid[38;5;241m.[39muuid4()),
[1;32m    275[0m     optional_args[38;5;241m=[39m[],
[1;32m    276[0m     library[38;5;241m=[39mlibrary,
[1;32m    277[0m )
[1;32m    279[0m [38;5;28mself[39m[38;5;241m.[39mbm[38;5;241m.[39msession[38;5;241m.[39madd(template)
[0;32m--> 280[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mbm[49m[38;5;241;43m.[39;49m[43msession[49m[38;5;241;43m.[39;49m[43mflush[49m[43m([49m[43m)[49m
[1;32m    282[0m [38;5;28;01mreturn[39;00m template

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3449[0m, in [0;36mSession.flush[0;34m(self, objects)[0m
[1;32m   3447[0m [38;5;28;01mtry[39;00m:
[1;32m   3448[0m     [38;5;28mself[39m[38;5;241m.[39m_flushing [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m-> 3449[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_flush[49m[43m([49m[43mobjects[49m[43m)[49m
[1;32m   3450[0m [38;5;28;01mfinally[39;00m:
[1;32m   3451[0m     [38;5;28mself[39m[38;5;241m.[39m_flushing [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3588[0m, in [0;36mSession._flush[0;34m(self, objects)[0m
[1;32m   3585[0m     transaction[38;5;241m.[39mcommit()
[1;32m   3587[0m [38;5;28;01mexcept[39;00m:
[0;32m-> 3588[0m [43m    [49m[38;5;28;43;01mwith[39;49;00m[43m [49m[43mutil[49m[38;5;241;43m.[39;49m[43msafe_reraise[49m[43m([49m[43m)[49m[43m:[49m
[1;32m   3589[0m [43m        [49m[43mtransaction[49m[38;5;241;43m.[39;49m[43mrollback[49m[43m([49m[43m_capture_exception[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py:70[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m     68[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[1;32m     69[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39mwarn_only:
[0;32m---> 70[0m         [43mcompat[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m     71[0m [43m            [49m[43mexc_value[49m[43m,[49m
[1;32m     72[0m [43m            [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_tb[49m[43m,[49m
[1;32m     73[0m [43m        [49m[43m)[49m
[1;32m     74[0m [38;5;28;01melse[39;00m:
[1;32m     75[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m compat[38;5;241m.[39mpy3k [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_exc_info[[38;5;241m1[39m]:
[1;32m     76[0m         [38;5;66;03m# emulate Py3K's behavior of telling us when an exception[39;00m
[1;32m     77[0m         [38;5;66;03m# occurs in an exception handler.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py:211[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    208[0m     exception[38;5;241m.[39m__cause__ [38;5;241m=[39m replace_context
[1;32m    210[0m [38;5;28;01mtry[39;00m:
[0;32m--> 211[0m     [38;5;28;01mraise[39;00m exception
[1;32m    212[0m [38;5;28;01mfinally[39;00m:
[1;32m    213[0m     [38;5;66;03m# credit to[39;00m
[1;32m    214[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    215[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m
[1;32m    216[0m     [38;5;28;01mdel[39;00m exception, replace_context, from_, with_traceback

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3549[0m, in [0;36mSession._flush[0;34m(self, objects)[0m
[1;32m   3547[0m [38;5;28mself[39m[38;5;241m.[39m_warn_on_events [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m   3548[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3549[0m     [43mflush_context[49m[38;5;241;43m.[39;49m[43mexecute[49m[43m([49m[43m)[49m
[1;32m   3550[0m [38;5;28;01mfinally[39;00m:
[1;32m   3551[0m     [38;5;28mself[39m[38;5;241m.[39m_warn_on_events [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py:456[0m, in [0;36mUOWTransaction.execute[0;34m(self)[0m
[1;32m    454[0m [38;5;28;01melse[39;00m:
[1;32m    455[0m     [38;5;28;01mfor[39;00m rec [38;5;129;01min[39;00m topological[38;5;241m.[39msort([38;5;28mself[39m[38;5;241m.[39mdependencies, postsort_actions):
[0;32m--> 456[0m         [43mrec[49m[38;5;241;43m.[39;49m[43mexecute[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py:630[0m, in [0;36mSaveUpdateAll.execute[0;34m(self, uow)[0m
[1;32m    628[0m [38;5;129m@util[39m[38;5;241m.[39mpreload_module([38;5;124m"[39m[38;5;124msqlalchemy.orm.persistence[39m[38;5;124m"[39m)
[1;32m    629[0m [38;5;28;01mdef[39;00m [38;5;21mexecute[39m([38;5;28mself[39m, uow):
[0;32m--> 630[0m     [43mutil[49m[38;5;241;43m.[39;49m[43mpreloaded[49m[38;5;241;43m.[39;49m[43morm_persistence[49m[38;5;241;43m.[39;49m[43msave_obj[49m[43m([49m
[1;32m    631[0m [43m        [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmapper[49m[43m,[49m
[1;32m    632[0m [43m        [49m[43muow[49m[38;5;241;43m.[39;49m[43mstates_for_mapper_hierarchy[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmapper[49m[43m,[49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m)[49m[43m,[49m
[1;32m    633[0m [43m        [49m[43muow[49m[43m,[49m
[1;32m    634[0m [43m    [49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py:245[0m, in [0;36msave_obj[0;34m(base_mapper, states, uowtransaction, single)[0m
[1;32m    233[0m     update [38;5;241m=[39m _collect_update_commands(
[1;32m    234[0m         uowtransaction, table, states_to_update
[1;32m    235[0m     )
[1;32m    237[0m     _emit_update_statements(
[1;32m    238[0m         base_mapper,
[1;32m    239[0m         uowtransaction,
[0;32m   (...)[0m
[1;32m    242[0m         update,
[1;32m    243[0m     )
[0;32m--> 245[0m     [43m_emit_insert_statements[49m[43m([49m
[1;32m    246[0m [43m        [49m[43mbase_mapper[49m[43m,[49m
[1;32m    247[0m [43m        [49m[43muowtransaction[49m[43m,[49m
[1;32m    248[0m [43m        [49m[43mmapper[49m[43m,[49m
[1;32m    249[0m [43m        [49m[43mtable[49m[43m,[49m
[1;32m    250[0m [43m        [49m[43minsert[49m[43m,[49m
[1;32m    251[0m [43m    [49m[43m)[49m
[1;32m    253[0m _finalize_insert_update_commands(
[1;32m    254[0m     base_mapper,
[1;32m    255[0m     uowtransaction,
[0;32m   (...)[0m
[1;32m    271[0m     ),
[1;32m    272[0m )

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py:1238[0m, in [0;36m_emit_insert_statements[0;34m(base_mapper, uowtransaction, mapper, table, insert, bookkeeping)[0m
[1;32m   1232[0m     result [38;5;241m=[39m connection[38;5;241m.[39m_execute_20(
[1;32m   1233[0m         statement[38;5;241m.[39mvalues(value_params),
[1;32m   1234[0m         params,
[1;32m   1235[0m         execution_options[38;5;241m=[39mexecution_options,
[1;32m   1236[0m     )
[1;32m   1237[0m [38;5;28;01melse[39;00m:
[0;32m-> 1238[0m     result [38;5;241m=[39m [43mconnection[49m[38;5;241;43m.[39;49m[43m_execute_20[49m[43m([49m
[1;32m   1239[0m [43m        [49m[43mstatement[49m[43m,[49m
[1;32m   1240[0m [43m        [49m[43mparams[49m[43m,[49m
[1;32m   1241[0m [43m        [49m[43mexecution_options[49m[38;5;241;43m=[39;49m[43mexecution_options[49m[43m,[49m
[1;32m   1242[0m [43m    [49m[43m)[49m
[1;32m   1244[0m primary_key [38;5;241m=[39m result[38;5;241m.[39minserted_primary_key
[1;32m   1245[0m [38;5;28;01mif[39;00m primary_key [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1710[0m, in [0;36mConnection._execute_20[0;34m(self, statement, parameters, execution_options)[0m
[1;32m   1706[0m     util[38;5;241m.[39mraise_(
[1;32m   1707[0m         exc[38;5;241m.[39mObjectNotExecutableError(statement), replace_context[38;5;241m=[39merr
[1;32m   1708[0m     )
[1;32m   1709[0m [38;5;28;01melse[39;00m:
[0;32m-> 1710[0m     [38;5;28;01mreturn[39;00m [43mmeth[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43margs_10style[49m[43m,[49m[43m [49m[43mkwargs_10style[49m[43m,[49m[43m [49m[43mexecution_options[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:334[0m, in [0;36mClauseElement._execute_on_connection[0;34m(self, connection, multiparams, params, execution_options, _force)[0m
[1;32m    330[0m [38;5;28;01mdef[39;00m [38;5;21m_execute_on_connection[39m(
[1;32m    331[0m     [38;5;28mself[39m, connection, multiparams, params, execution_options, _force[38;5;241m=[39m[38;5;28;01mFalse[39;00m
[1;32m    332[0m ):
[1;32m    333[0m     [38;5;28;01mif[39;00m _force [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39msupports_execution:
[0;32m--> 334[0m         [38;5;28;01mreturn[39;00m [43mconnection[49m[38;5;241;43m.[39;49m[43m_execute_clauseelement[49m[43m([49m
[1;32m    335[0m [43m            [49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mmultiparams[49m[43m,[49m[43m [49m[43mparams[49m[43m,[49m[43m [49m[43mexecution_options[49m
[1;32m    336[0m [43m        [49m[43m)[49m
[1;32m    337[0m     [38;5;28;01melse[39;00m:
[1;32m    338[0m         [38;5;28;01mraise[39;00m exc[38;5;241m.[39mObjectNotExecutableError([38;5;28mself[39m)

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1577[0m, in [0;36mConnection._execute_clauseelement[0;34m(self, elem, multiparams, params, execution_options)[0m
[1;32m   1565[0m compiled_cache [38;5;241m=[39m execution_options[38;5;241m.[39mget(
[1;32m   1566[0m     [38;5;124m"[39m[38;5;124mcompiled_cache[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39mengine[38;5;241m.[39m_compiled_cache
[1;32m   1567[0m )
[1;32m   1569[0m compiled_sql, extracted_params, cache_hit [38;5;241m=[39m elem[38;5;241m.[39m_compile_w_cache(
[1;32m   1570[0m     dialect[38;5;241m=[39mdialect,
[1;32m   1571[0m     compiled_cache[38;5;241m=[39mcompiled_cache,
[0;32m   (...)[0m
[1;32m   1575[0m     linting[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mdialect[38;5;241m.[39mcompiler_linting [38;5;241m|[39m compiler[38;5;241m.[39mWARN_LINTING,
[1;32m   1576[0m )
[0;32m-> 1577[0m ret [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_execute_context[49m[43m([49m
[1;32m   1578[0m [43m    [49m[43mdialect[49m[43m,[49m
[1;32m   1579[0m [43m    [49m[43mdialect[49m[38;5;241;43m.[39;49m[43mexecution_ctx_cls[49m[38;5;241;43m.[39;49m[43m_init_compiled[49m[43m,[49m
[1;32m   1580[0m [43m    [49m[43mcompiled_sql[49m[43m,[49m
[1;32m   1581[0m [43m    [49m[43mdistilled_params[49m[43m,[49m
[1;32m   1582[0m [43m    [49m[43mexecution_options[49m[43m,[49m
[1;32m   1583[0m [43m    [49m[43mcompiled_sql[49m[43m,[49m
[1;32m   1584[0m [43m    [49m[43mdistilled_params[49m[43m,[49m
[1;32m   1585[0m [43m    [49m[43melem[49m[43m,[49m
[1;32m   1586[0m [43m    [49m[43mextracted_params[49m[43m,[49m
[1;32m   1587[0m [43m    [49m[43mcache_hit[49m[38;5;241;43m=[39;49m[43mcache_hit[49m[43m,[49m
[1;32m   1588[0m [43m[49m[43m)[49m
[1;32m   1589[0m [38;5;28;01mif[39;00m has_events:
[1;32m   1590[0m     [38;5;28mself[39m[38;5;241m.[39mdispatch[38;5;241m.[39mafter_execute(
[1;32m   1591[0m         [38;5;28mself[39m,
[1;32m   1592[0m         elem,
[0;32m   (...)[0m
[1;32m   1596[0m         ret,
[1;32m   1597[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1953[0m, in [0;36mConnection._execute_context[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)[0m
[1;32m   1950[0m             branched[38;5;241m.[39mclose()
[1;32m   1952[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m-> 1953[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception[49m[43m([49m
[1;32m   1954[0m [43m        [49m[43me[49m[43m,[49m[43m [49m[43mstatement[49m[43m,[49m[43m [49m[43mparameters[49m[43m,[49m[43m [49m[43mcursor[49m[43m,[49m[43m [49m[43mcontext[49m
[1;32m   1955[0m [43m    [49m[43m)[49m
[1;32m   1957[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2134[0m, in [0;36mConnection._handle_dbapi_exception[0;34m(self, e, statement, parameters, cursor, context)[0m
[1;32m   2132[0m     util[38;5;241m.[39mraise_(newraise, with_traceback[38;5;241m=[39mexc_info[[38;5;241m2[39m], from_[38;5;241m=[39me)
[1;32m   2133[0m [38;5;28;01melif[39;00m should_wrap:
[0;32m-> 2134[0m     [43mutil[49m[38;5;241;43m.[39;49m[43mraise_[49m[43m([49m
[1;32m   2135[0m [43m        [49m[43msqlalchemy_exception[49m[43m,[49m[43m [49m[43mwith_traceback[49m[38;5;241;43m=[39;49m[43mexc_info[49m[43m[[49m[38;5;241;43m2[39;49m[43m][49m[43m,[49m[43m [49m[43mfrom_[49m[38;5;241;43m=[39;49m[43me[49m
[1;32m   2136[0m [43m    [49m[43m)[49m
[1;32m   2137[0m [38;5;28;01melse[39;00m:
[1;32m   2138[0m     util[38;5;241m.[39mraise_(exc_info[[38;5;241m1[39m], with_traceback[38;5;241m=[39mexc_info[[38;5;241m2[39m])

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/util/compat.py:211[0m, in [0;36mraise_[0;34m(***failed resolving arguments***)[0m
[1;32m    208[0m     exception[38;5;241m.[39m__cause__ [38;5;241m=[39m replace_context
[1;32m    210[0m [38;5;28;01mtry[39;00m:
[0;32m--> 211[0m     [38;5;28;01mraise[39;00m exception
[1;32m    212[0m [38;5;28;01mfinally[39;00m:
[1;32m    213[0m     [38;5;66;03m# credit to[39;00m
[1;32m    214[0m     [38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/[39;00m
[1;32m    215[0m     [38;5;66;03m# as the __traceback__ object creates a cycle[39;00m
[1;32m    216[0m     [38;5;28;01mdel[39;00m exception, replace_context, from_, with_traceback

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1910[0m, in [0;36mConnection._execute_context[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)[0m
[1;32m   1908[0m                 [38;5;28;01mbreak[39;00m
[1;32m   1909[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m evt_handled:
[0;32m-> 1910[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdialect[49m[38;5;241;43m.[39;49m[43mdo_execute[49m[43m([49m
[1;32m   1911[0m [43m            [49m[43mcursor[49m[43m,[49m[43m [49m[43mstatement[49m[43m,[49m[43m [49m[43mparameters[49m[43m,[49m[43m [49m[43mcontext[49m
[1;32m   1912[0m [43m        [49m[43m)[49m
[1;32m   1914[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_has_events [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39mengine[38;5;241m.[39m_has_events:
[1;32m   1915[0m     [38;5;28mself[39m[38;5;241m.[39mdispatch[38;5;241m.[39mafter_cursor_execute(
[1;32m   1916[0m         [38;5;28mself[39m,
[1;32m   1917[0m         cursor,
[0;32m   (...)[0m
[1;32m   1921[0m         context[38;5;241m.[39mexecutemany,
[1;32m   1922[0m     )

File [0;32m/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sqlalchemy/engine/default.py:736[0m, in [0;36mDefaultDialect.do_execute[0;34m(self, cursor, statement, parameters, context)[0m
[1;32m    735[0m [38;5;28;01mdef[39;00m [38;5;21mdo_execute[39m([38;5;28mself[39m, cursor, statement, parameters, context[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 736[0m     cursor[38;5;241m.[39mexecute(statement, parameters)

[0;31mIntegrityError[0m: (sqlite3.IntegrityError) UNIQUE constraint failed: template.name, template.library_id
[SQL: INSERT INTO template (name, body_id, optional_args, library_id) VALUES (?, ?, ?, ?)]
[parameters: ('primary-only-loop', 'e78d958d-aa01-4655-a350-ff5d8617b18c', '[]', 3)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: template.name, template.library_id
[SQL: INSERT INTO template (name, body_id, optional_args, library_id) VALUES (?, ?, ?, ?)]
[parameters: ('primary-only-loop', 'e78d958d-aa01-4655-a350-ff5d8617b18c', '[]', 3)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

